// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cec_cpp_choose_clusters
Rcpp::List cec_cpp_choose_clusters(const arma::mat& logdens, const arma::vec& nu);
RcppExport SEXP _CEClust_cec_cpp_choose_clusters(SEXP logdensSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type logdens(logdensSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(cec_cpp_choose_clusters(logdens, nu));
    return rcpp_result_gen;
END_RCPP
}
// cec_cpp_phi_from_clusters
Rcpp::NumericVector cec_cpp_phi_from_clusters(const IntegerVector& clusters, int r);
RcppExport SEXP _CEClust_cec_cpp_phi_from_clusters(SEXP clustersSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(cec_cpp_phi_from_clusters(clusters, r));
    return rcpp_result_gen;
END_RCPP
}
// cec_cpp_gaussian_stats
Rcpp::List cec_cpp_gaussian_stats(const arma::mat& X, const IntegerVector& clusters, int r);
RcppExport SEXP _CEClust_cec_cpp_gaussian_stats(SEXP XSEXP, SEXP clustersSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(cec_cpp_gaussian_stats(X, clusters, r));
    return rcpp_result_gen;
END_RCPP
}
// cec_cpp_logdens_gaussian
arma::mat cec_cpp_logdens_gaussian(const arma::mat& X, const arma::mat& means, const List& sigma_list, double lambda);
RcppExport SEXP _CEClust_cec_cpp_logdens_gaussian(SEXP XSEXP, SEXP meansSEXP, SEXP sigma_listSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type means(meansSEXP);
    Rcpp::traits::input_parameter< const List& >::type sigma_list(sigma_listSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(cec_cpp_logdens_gaussian(X, means, sigma_list, lambda));
    return rcpp_result_gen;
END_RCPP
}
// cec_cpp_discrete_counts
Rcpp::List cec_cpp_discrete_counts(const IntegerMatrix& X, const IntegerVector& clusters, int r, int n_levels);
RcppExport SEXP _CEClust_cec_cpp_discrete_counts(SEXP XSEXP, SEXP clustersSEXP, SEXP rSEXP, SEXP n_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type n_levels(n_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cec_cpp_discrete_counts(X, clusters, r, n_levels));
    return rcpp_result_gen;
END_RCPP
}
// cec_cpp_logdens_discrete
arma::mat cec_cpp_logdens_discrete(const IntegerMatrix& X, const List& prob_list);
RcppExport SEXP _CEClust_cec_cpp_logdens_discrete(SEXP XSEXP, SEXP prob_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const List& >::type prob_list(prob_listSEXP);
    rcpp_result_gen = Rcpp::wrap(cec_cpp_logdens_discrete(X, prob_list));
    return rcpp_result_gen;
END_RCPP
}
// cec_cpp_cluster_fingerprint
double cec_cpp_cluster_fingerprint(const IntegerVector& clusters);
RcppExport SEXP _CEClust_cec_cpp_cluster_fingerprint(SEXP clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type clusters(clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(cec_cpp_cluster_fingerprint(clusters));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CEClust_cec_cpp_choose_clusters", (DL_FUNC) &_CEClust_cec_cpp_choose_clusters, 2},
    {"_CEClust_cec_cpp_phi_from_clusters", (DL_FUNC) &_CEClust_cec_cpp_phi_from_clusters, 2},
    {"_CEClust_cec_cpp_gaussian_stats", (DL_FUNC) &_CEClust_cec_cpp_gaussian_stats, 3},
    {"_CEClust_cec_cpp_logdens_gaussian", (DL_FUNC) &_CEClust_cec_cpp_logdens_gaussian, 4},
    {"_CEClust_cec_cpp_discrete_counts", (DL_FUNC) &_CEClust_cec_cpp_discrete_counts, 4},
    {"_CEClust_cec_cpp_logdens_discrete", (DL_FUNC) &_CEClust_cec_cpp_logdens_discrete, 2},
    {"_CEClust_cec_cpp_cluster_fingerprint", (DL_FUNC) &_CEClust_cec_cpp_cluster_fingerprint, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_CEClust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
