# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cec_cpp_sample_int_replace <- function(r, n) {
    .Call(`_CEClust_cec_cpp_sample_int_replace`, r, n)
}

cec_cpp_choose_clusters <- function(logdens, nu) {
    .Call(`_CEClust_cec_cpp_choose_clusters`, logdens, nu)
}

cec_cpp_choose_clusters_from_logdens <- function(logdens, nu, lambda) {
    .Call(`_CEClust_cec_cpp_choose_clusters_from_logdens`, logdens, nu, lambda)
}

cec_cpp_gauss_univ_assign <- function(z, nu, m, s, lambda) {
    .Call(`_CEClust_cec_cpp_gauss_univ_assign`, z, nu, m, s, lambda)
}

cec_cpp_gauss_univ_cluster_sums <- function(z, clusters, r) {
    .Call(`_CEClust_cec_cpp_gauss_univ_cluster_sums`, z, clusters, r)
}

cec_cpp_gauss_univ_cluster_sums_known_counts <- function(z, clusters, r) {
    .Call(`_CEClust_cec_cpp_gauss_univ_cluster_sums_known_counts`, z, clusters, r)
}

cec_cpp_gauss_univ_params_known_counts <- function(z, clusters, counts, r, lambda, C) {
    .Call(`_CEClust_cec_cpp_gauss_univ_params_known_counts`, z, clusters, counts, r, lambda, C)
}

cec_cpp_compress_integer_clusters_info <- function(clusters, r) {
    .Call(`_CEClust_cec_cpp_compress_integer_clusters_info`, clusters, r)
}

cec_cpp_compress_integer_clusters_info_fingerprint <- function(clusters, r, weights) {
    .Call(`_CEClust_cec_cpp_compress_integer_clusters_info_fingerprint`, clusters, r, weights)
}

cec_cpp_gauss_univ_compress_params_fingerprint <- function(z, clusters, r, weights, lambda, C) {
    .Call(`_CEClust_cec_cpp_gauss_univ_compress_params_fingerprint`, z, clusters, r, weights, lambda, C)
}

cec_cpp_gauss_univ_params_from_phiM <- function(z, phiM, lambda, C) {
    .Call(`_CEClust_cec_cpp_gauss_univ_params_from_phiM`, z, phiM, lambda, C)
}

cec_cpp_gauss_univ_perturb_warm_phiM <- function(phi, r, nu, n) {
    .Call(`_CEClust_cec_cpp_gauss_univ_perturb_warm_phiM`, phi, r, nu, n)
}

cec_cpp_gauss_univ_expand_phi_random <- function(phi, n) {
    .Call(`_CEClust_cec_cpp_gauss_univ_expand_phi_random`, phi, n)
}

cec_cpp_phi_from_clusters <- function(clusters, r) {
    .Call(`_CEClust_cec_cpp_phi_from_clusters`, clusters, r)
}

cec_cpp_gaussian_stats <- function(X, clusters, r) {
    .Call(`_CEClust_cec_cpp_gaussian_stats`, X, clusters, r)
}

cec_cpp_logdens_gaussian <- function(X, means, sigma_list, lambda) {
    .Call(`_CEClust_cec_cpp_logdens_gaussian`, X, means, sigma_list, lambda)
}

cec_cpp_discrete_counts <- function(X, clusters, r, n_levels) {
    .Call(`_CEClust_cec_cpp_discrete_counts`, X, clusters, r, n_levels)
}

cec_cpp_logdens_discrete <- function(X, prob_list) {
    .Call(`_CEClust_cec_cpp_logdens_discrete`, X, prob_list)
}

cec_cpp_cluster_fingerprint <- function(clusters) {
    .Call(`_CEClust_cec_cpp_cluster_fingerprint`, clusters)
}

