# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cec_cpp_choose_clusters <- function(logdens, nu) {
    .Call("_CEClust_cec_cpp_choose_clusters", PACKAGE = "CEClust", logdens, nu)
}

cec_cpp_phi_from_clusters <- function(clusters, r) {
    .Call("_CEClust_cec_cpp_phi_from_clusters", PACKAGE = "CEClust", clusters, r)
}

cec_cpp_gaussian_stats <- function(X, clusters, r) {
    .Call("_CEClust_cec_cpp_gaussian_stats", PACKAGE = "CEClust", X, clusters, r)
}

cec_cpp_logdens_gaussian <- function(X, means, sigma_list, lambda) {
    .Call("_CEClust_cec_cpp_logdens_gaussian", PACKAGE = "CEClust", X, means, sigma_list, lambda)
}

cec_cpp_discrete_counts <- function(X, clusters, r, n_levels) {
    .Call("_CEClust_cec_cpp_discrete_counts", PACKAGE = "CEClust", X, clusters, r, n_levels)
}

cec_cpp_logdens_discrete <- function(X, prob_list) {
    .Call("_CEClust_cec_cpp_logdens_discrete", PACKAGE = "CEClust", X, prob_list)
}

cec_cpp_cluster_fingerprint <- function(clusters) {
    .Call("_CEClust_cec_cpp_cluster_fingerprint", PACKAGE = "CEClust", clusters)
}

